@base_address = http://localhost:5288/api/admin/orders
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluQGV4YW1wbGUuY29tIiwianRpIjoiODNhZGFlOTgtNTQ2Mi00MjhmLTliMGUtODlkNGIxMzRjZTMzIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzkxNDQ4NTcxLCJleHAiOjE3OTE0NDk0NzEsImlhdCI6MTc5MTQ0ODU3MSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzA4NCIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcwODQifQ.mJO75B8rgVLQqyFvxCdDPROv4DhEoTLiDH9aOUeXne8

###
GET {{base_address}}
Authorization: Bearer {{accessToken}}

### GET single order
GET {{base_address}}/2
Authorization: Bearer {{accessToken}}

###
POST {{base_address}}/change-payment-status
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "OrderId":2,
    "PaymentStatus":"paid"
}

###
POST {{base_address}}/change-order-status
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "OrderId":2,
    "OrderStatus":"Confirmed"
}