@base_url = http://localhost:5288/api/cart
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImpvaG5AZXhhbXBsZS5jb20iLCJqdGkiOiI0NGYyNjVhMS1jYjNjLTRkYzktOGI2NC1kMTliMjI2MjNkYzciLCJyb2xlIjoiVXNlciIsIm5iZiI6MTc4OTEzMDQ4MCwiZXhwIjoxNzg5MTMxMzgwLCJpYXQiOjE3ODkxMzA0ODAsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwODQiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MDg0In0.4pt1CHRvkzoqaoW7PFBq2VI9K1reGHLp8zQqNdPbZX8

### userCart 
GET {{base_url}}
Authorization: Bearer {{accessToken}}

### add Item
POST {{base_url}}/items
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
   "bookId":2,
   "quantity":2
}

### Update cart item (increment/decrement)
### /items/{cartItemId}
PUT  {{base_url}}/items/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "Quantity": 0
}

### Empty cart collection 
DELETE {{base_url}}/items
Authorization: Bearer {{accessToken}}