@base_url = http://localhost:5288/api/cart
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImpvaG5AZXhhbXBsZS5jb20iLCJqdGkiOiIzMjUxYTVkNi04YWUzLTQ4NTItYmRjNy1hOGIyYmRhZTk0M2EiLCJyb2xlIjoiVXNlciIsIm5iZiI6MTc4ODMzMjA2MywiZXhwIjoxNzg4MzMyOTYzLCJpYXQiOjE3ODgzMzIwNjMsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwODQiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MDg0In0.6GlrDO7JEijrfC0-0BXPztaxIszFJglpfhPoKYPKeyg

### userCart 
GET {{base_url}}
Authorization: Bearer {{accessToken}}

### add Item
POST {{base_url}}/items
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
   "bookId":2,
   "quantity":1
}

### Update cart item (increment/decrement)
### /items/{cartItemId}
PUT  {{base_url}}/items/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "Quantity": 0
}

### Empty cart collection 
DELETE {{base_url}}/items
Authorization: Bearer {{accessToken}}