@base_address = http://localhost:5288/api/auth

POST {{base_address}}/signup
Content-Type: application/json

{
  "name":"Manish Rawat",
  "email": "manishrawat@example.com",
  "password": "Manish@123"
}
###

POST {{base_address}}/login
Content-Type: application/json

{
  "username":"manishrawat@example.com",
  "password": "Manish@123"
}
