@base_address = http://localhost:5288/api/auth
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImpvaG5AZXhhbXBsZS5jb20iLCJqdGkiOiI4YmJhOWZmNS03MzdhLTQ5N2UtYWI2YS03Zjg4NjE1NDY4YzQiLCJyb2xlIjoiVXNlciIsIm5iZiI6MTc4NzkxMzY3NSwiZXhwIjoxNzg3OTEzNzM1LCJpYXQiOjE3ODc5MTM2NzUsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwODQiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MDg0In0.emgeQ6WPYGy_AFhUMJNlN4bl93UFOoAK2JhyUx7PicU

POST {{base_address}}/signup
Content-Type: application/json

{
  "name":"John Doe",
  "email": "john@example.com",
  "password": "John@123"
}
###

POST {{base_address}}/login
Content-Type: application/json

{
  "username":"john@example.com",
  "password": "John@123"
}

###
POST {{base_address}}/refresh
Content-Type: application/json

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hbmlzaHJhd2F0QGV4YW1wbGUuY29tIiwianRpIjoiODFmNGNiMTQtNzczNi00Y2FmLTgwMTItMjViN2M4NTY5ZTI0Iiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3ODc1NTY2MTgsImV4cCI6MTc4NzU1NjY3OCwiaWF0IjoxNzg3NTU2NjE4LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDg0IiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzA4NCJ9.BxBQqfnPSLDbDK6LxUBAZzeRlYq7q6rysZaeCTp7u4U",
  "refreshToken": "eafb5da25f304e92944ede20b173c884"
}

### logout
POST {{base_address}}/logout
Authorization: Bearer {{accessToken}}

### userinfo
GET {{base_address}}/me
Authorization: Bearer {{accessToken}}

### protected route
GET http://localhost:5288/weatherforecast
Authorization: Bearer {{accessToken}}